sudo: false
language: java

jdk:
  - openjdk11

script: mvn clean verify

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: script
  script: mvn deploy --settings .travis/settings.xml -DskipTests=true --batch-mode --update-snapshots -Prelease
  on:
    branch: master